/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ventanas.emergentes;

import Modelo.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Rodrigo
 */
public class VehiculoCrear extends javax.swing.JInternalFrame {

    private Sistema sis;
    DefaultComboBoxModel<String> model;

    /**
     * Creates new form VehiculoCrear
     *
     * @param s
     */
    public VehiculoCrear(Sistema s) {
        initComponents();
        Icon icon = new ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\imagenes\\minicon\\circulo-de-usuario.png");
        this.setFrameIcon(icon);
        this.sis = s;
        this.model = new DefaultComboBoxModel<>();
        Timer t = new Timer(1000, e -> setVehiculos());
        t.start();
    }

    private void setVehiculos() {
        model.removeAllElements();
        Usuario us = sis.obtenerSesion();
        if (us instanceof Administrativo admin) {

            for (Vehiculo v : admin.listarVehiculo()) {
                model.addElement(v.getDominio());
            }
            autos.setModel(model);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        asignar = new javax.swing.JButton();
        autos = new javax.swing.JComboBox<>();
        Agregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Asignar vehículo");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Transportista DNI:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Vehículo:");

        tp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        asignar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        asignar.setText("Asignar");
        asignar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarActionPerformed(evt);
            }
        });

        autos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        autos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Agregar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(autos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(autos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asignar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // Campos del dialogo
        JTextField tfMarca = new JTextField();
        JTextField tfModelo = new JTextField();
        JTextField tfDominio = new JTextField();
        JTextField tfCapacidad = new JTextField();

// Crear el pane y agregar los campos
        Object[] inputs = {
            "Marca", tfMarca,
            "Modelo", tfModelo,
            "Dominio", tfDominio,
            "Capacidad de carga", tfCapacidad
        };

        int result = JOptionPane.showConfirmDialog(null, inputs, "Nuevo vehículo", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {

            // Obtener valores de los campos
            String marca = tfMarca.getText();
            String modelo = tfModelo.getText();
            String dominio = tfDominio.getText();
            int capacidad = Integer.parseInt(tfCapacidad.getText());

            // Crear el objeto
            Vehiculo vehiculo = new Vehiculo(marca, modelo, dominio, capacidad);
            Usuario us = sis.obtenerSesion();
            if (us instanceof Gerente gen) {
                try {
                    gen.crearVehiculo(vehiculo);
                } catch (Exception ex) {
                    Logger.getLogger(VehiculoCrear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            setVehiculos();
            // Mensaje de confirmación  
            JOptionPane.showMessageDialog(null, "Vehículo creado");

        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarActionPerformed
        try {
            Usuario us = sis.obtenerSesion();
            if (us instanceof Gerente gen) {
                gen.asignarVehiculo(gen.buscarTransportista(tp.getText()), gen.buscarVehiculoPorDominio((String) autos.getSelectedItem()));
                JOptionPane.showMessageDialog(this, "Vehículo asignado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_asignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton asignar;
    private javax.swing.JComboBox<String> autos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}
